### ISSUE TITLE
Unable to install deb file on debian 13

### ISSUE THREAD

**Issue by syntesys** [jetm/mediatek-mt7927-dkms#71]
Hello all,
I have an ASUS ROG X870E Crosshair Hero with debian 13, and I'm trying to install the precompiled deb package, with the following errors:

`sudo apt install ./mediatek-mt7927-dkms*.deb

Note, selecting 'mediatek-mt7927-dkms' instead of './mediatek-mt7927-dkms_2.11-1_all.deb'
Installing:
  mediatek-mt7927-dkms

Summary:
  Upgrading: 0, Installing: 1, Removing: 0, Not Upgrading: 56
  Download size: 0 B / 2.845 kB
  Space needed: 0 B / 55,5 GB available

Get:1 /home/syntesys/mediatek-mt7927-dkms_2.11-1_all.deb mediatek-mt7927-dkms all 2.11-1 [2.845 kB]
Selecting previously unselected package mediatek-mt7927-dkms.
(Reading database ... 327179 files and directories currently installed.)
Preparing to unpack .../mediatek-mt7927-dkms_2.11-1_all.deb ...
Unpacking mediatek-mt7927-dkms (2.11-1) ...
Setting up mediatek-mt7927-dkms (2.11-1) ...
Creating symlink /var/lib/dkms/mediatek-mt7927/2.11/source -> /usr/src/mediatek-mt7927-2.11
Sign command: /lib/modules/6.12.85+deb13-amd64/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub

Building module(s)...(bad exit status: 2)
Failed command:
if ! grep -q 'MT6639' /lib/modules/6.12.85+deb13-amd64/build/drivers/bluetooth/btmtk.h 2>/dev/null; then make -C /lib/modules/6.12.85+deb13-amd64/build M=/var/lib/dkms/mediatek-mt7927/2.11/build/drivers/bluetooth modules; fi && make -C /lib/modules/6.12.85+deb13-amd64/build M=/var/lib/dkms/mediatek-mt7927/2.11/build/mt76 modules

Error! Bad return status for module build on kernel: 6.12.85+deb13-amd64 (x86_64)
Consult /var/lib/dkms/mediatek-mt7927/2.11/build/make.log for more information.
Sign command: /lib/modules/6.12.85+deb13-amd64/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub

Building module(s)...(bad exit status: 2)
Failed command:
if ! grep -q 'MT6639' /lib/modules/6.12.85+deb13-amd64/build/drivers/bluetooth/btmtk.h 2>/dev/null; then make -C /lib/modules/6.12.85+deb13-amd64/build M=/var/lib/dkms/mediatek-mt7927/2.11/build/drivers/bluetooth modules; fi && make -C /lib/modules/6.12.85+deb13-amd64/build M=/var/lib/dkms/mediatek-mt7927/2.11/build/mt76 modules

Error! Bad return status for module build on kernel: 6.12.85+deb13-amd64 (x86_64)
Consult /var/lib/dkms/mediatek-mt7927/2.11/build/make.log for more information.
`

Log:
`cat /var/lib/dkms/mediatek-mt7927/2.11/build/make.log
DKMS (dkms-3.2.2) make.log for mediatek-mt7927/2.11 for kernel 6.12.85+deb13-amd64 (x86_64)
gio 14 mag 2026, 11:58:10, CEST

Building module(s)
# command: if ! grep -q 'MT6639' /lib/modules/6.12.85+deb13-amd64/build/drivers/bluetooth/btmtk.h 2>/dev/null; then make -C /lib/modules/6.12.85+deb13-amd64/build M=/var/lib/dkms/mediatek-mt7927/2.11/build/drivers/bluetooth modules; fi && make -C /lib/modules/6.12.85+deb13-amd64/build M=/var/lib/dkms/mediatek-mt7927/2.11/build/mt76 modules
make: Entering directory '/usr/src/linux-headers-6.12.85+deb13-amd64'
  CC [M]  /var/lib/dkms/mediatek-mt7927/2.11/build/drivers/bluetooth/btusb.o
/var/lib/dkms/mediatek-mt7927/2.11/build/drivers/bluetooth/btusb.c:24:10: fatal error: net/bluetooth/hci_drv.h: No such file or directory
   24 | #include <net/bluetooth/hci_drv.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [/usr/src/linux-headers-6.12.85+deb13-common/scripts/Makefile.build:234: /var/lib/dkms/mediatek-mt7927/2.11/build/drivers/bluetooth/btusb.o] Error 1
make[1]: *** [/usr/src/linux-headers-6.12.85+deb13-common/Makefile:1980: /var/lib/dkms/mediatek-mt7927/2.11/build/drivers/bluetooth] Error 2
make: *** [/usr/src/linux-headers-6.12.85+deb13-common/Makefile:236: __sub-make] Error 2
make: Leaving directory '/usr/src/linux-headers-6.12.85+deb13-amd64'

# exit code: 2
# elapsed time: 00:00:00
----------------------------------------------------------------
`

**Comment by jetm** [comment]
Hi,

Kernel 6.12 is below the minimum requirement of 6.17. The header `net/bluetooth/hci_drv.h` referenced in the build error was introduced in 6.17, so the failure is expected.

Debian 13 ships 6.12 in its stable kernel. You would need a backport kernel (6.17+) for this to work.

See #77 for a note on response times.

**Comment by jetm** [comment]
Closing this: the build failure is Debian 13's kernel being too old. The driver needs 6.17 or newer (it pulls in `net/bluetooth/hci_drv.h`, which landed in 6.17), and Debian 13 stable ships 6.12. A backports kernel at 6.17+ builds it fine. Reopen if it still fails on a 6.17+ kernel.
